"""Initial migration

Revision ID: 517310327b3e
Revises: 
Create Date: 2025-12-20 01:26:07.910850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '517310327b3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_research_types_id'), 'research_types', ['id'], unique=False)
    op.drop_table('phase_submissions')
    op.drop_table('review_templates')
    op.drop_index('name', table_name='mdm_titles')
    op.drop_table('mdm_titles')
    op.drop_index('role_permissions_permission_id_role_id_unique', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_table('user_tags')
    op.drop_index('code', table_name='mdm_departments')
    op.drop_table('mdm_departments')
    op.drop_table('user_roles')
    op.drop_table('system_settings')
    op.drop_index('name', table_name='research_categories')
    op.drop_table('research_categories')
    op.drop_table('project_phases')
    op.drop_index('code', table_name='roles')
    op.drop_index('name', table_name='roles')
    op.drop_table('roles')
    op.drop_table('project_notices')
    op.drop_index('code', table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('user_profile_settings')
    op.drop_index('name', table_name='research_tags')
    op.drop_table('research_tags')
    op.alter_column('audit_logs', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('audit_logs', 'target_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_constraint('audit_logs_ibfk_1', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.alter_column('research_collaborators', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('research_collaborators', 'item_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('research_collaborators', 'user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_research_collaborators_id'), 'research_collaborators', ['id'], unique=False)
    op.drop_constraint('research_collaborators_ibfk_2', 'research_collaborators', type_='foreignkey')
    op.drop_constraint('research_collaborators_ibfk_1', 'research_collaborators', type_='foreignkey')
    op.create_foreign_key(None, 'research_collaborators', 'research_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'research_collaborators', 'users', ['user_id'], ['id'])
    op.drop_column('research_collaborators', 'role')
    op.drop_column('research_collaborators', 'is_confirmed')
    op.alter_column('research_items', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('research_items', 'user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('research_items', 'subtype_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('research_items', 'status',
               existing_type=mysql.ENUM('draft', 'pending', 'approved', 'rejected', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('research_items', 'file_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('research_items', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('research_items', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_research_items_id'), 'research_items', ['id'], unique=False)
    op.drop_constraint('research_items_ibfk_1', 'research_items', type_='foreignkey')
    op.drop_constraint('research_items_ibfk_2', 'research_items', type_='foreignkey')
    op.create_foreign_key(None, 'research_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'research_items', 'research_subtypes', ['subtype_id'], ['id'])
    op.drop_column('research_items', 'submit_time')
    op.add_column('research_subtypes', sa.Column('type_id', sa.Integer(), nullable=False))
    op.alter_column('research_subtypes', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('research_subtypes', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_research_subtypes_id'), 'research_subtypes', ['id'], unique=False)
    op.drop_constraint('research_subtypes_ibfk_1', 'research_subtypes', type_='foreignkey')
    op.create_foreign_key(None, 'research_subtypes', 'research_types', ['type_id'], ['id'])
    op.drop_column('research_subtypes', 'template_url')
    op.drop_column('research_subtypes', 'category_id')
    op.drop_column('research_subtypes', 'is_active')
    op.drop_column('research_subtypes', 'required_fields_json')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'real_name')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'dept_id')
    op.drop_column('users', 'username')
    op.drop_column('users', 'title_id')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.add_column('users', sa.Column('title_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('users', sa.Column('dept_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.add_column('users', sa.Column('real_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('users', sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False))
    op.create_foreign_key('users_ibfk_2', 'users', 'mdm_titles', ['title_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('users_ibfk_1', 'users', 'mdm_departments', ['dept_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    op.add_column('research_subtypes', sa.Column('required_fields_json', mysql.JSON(), nullable=True))
    op.add_column('research_subtypes', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.add_column('research_subtypes', sa.Column('category_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('research_subtypes', sa.Column('template_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'research_subtypes', type_='foreignkey')
    op.create_foreign_key('research_subtypes_ibfk_1', 'research_subtypes', 'research_categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_research_subtypes_id'), table_name='research_subtypes')
    op.alter_column('research_subtypes', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.alter_column('research_subtypes', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('research_subtypes', 'type_id')
    op.add_column('research_items', sa.Column('submit_time', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'research_items', type_='foreignkey')
    op.drop_constraint(None, 'research_items', type_='foreignkey')
    op.create_foreign_key('research_items_ibfk_2', 'research_items', 'research_subtypes', ['subtype_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('research_items_ibfk_1', 'research_items', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.drop_index(op.f('ix_research_items_id'), table_name='research_items')
    op.alter_column('research_items', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('research_items', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('research_items', 'file_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('research_items', 'status',
               existing_type=mysql.ENUM('draft', 'pending', 'approved', 'rejected', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('research_items', 'subtype_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('research_items', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('research_items', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('research_collaborators', sa.Column('is_confirmed', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('research_collaborators', sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_constraint(None, 'research_collaborators', type_='foreignkey')
    op.drop_constraint(None, 'research_collaborators', type_='foreignkey')
    op.create_foreign_key('research_collaborators_ibfk_1', 'research_collaborators', 'research_items', ['item_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('research_collaborators_ibfk_2', 'research_collaborators', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.drop_index(op.f('ix_research_collaborators_id'), table_name='research_collaborators')
    op.alter_column('research_collaborators', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('research_collaborators', 'item_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    op.alter_column('research_collaborators', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_ibfk_1', 'audit_logs', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('audit_logs', 'ip',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'target_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('research_tags',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'research_tags', ['name'], unique=True)
    op.create_table('user_profile_settings',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_public_profile', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('show_funding', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_profile_settings_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('permissions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('module', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'permissions', ['code'], unique=True)
    op.create_table('project_notices',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('publish_by', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('is_system', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'roles', ['name'], unique=True)
    op.create_index('code', 'roles', ['code'], unique=True)
    op.create_table('project_phases',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('notice_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('deadline', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['project_notices.id'], name='project_phases_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('research_categories',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'research_categories', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('settings_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('settings_value', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('settings_key'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_roles',
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'user_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mdm_departments',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('level', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'mdm_departments', ['code'], unique=True)
    op.create_table('user_tags',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['research_tags.id'], name='user_tags_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_tags_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_permissions_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('role_permissions_permission_id_role_id_unique', 'role_permissions', ['role_id', 'permission_id'], unique=True)
    op.create_table('mdm_titles',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'mdm_titles', ['name'], unique=True)
    op.create_table('review_templates',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('is_shared', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='review_templates_ibfk_1', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('phase_submissions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('phase_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('applicant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('not_started', 'submitted', 'returned'), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('submitted_at', mysql.DATETIME(), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], name='phase_submissions_ibfk_2', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['project_phases.id'], name='phase_submissions_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_research_types_id'), table_name='research_types')
    op.drop_table('research_types')
    # ### end Alembic commands ###
